# Python basics

In [7]:
import os, shutil 


In [3]:
os.path.isfile("../favicon.png")

True

In [245]:
from pathlib import Path

In [249]:
Path("./test")
with open("./test", "w"): pass


In [6]:
shutil.copy("../favicon.png", "favicon.png")

'favicon.png'

In [10]:
os.path.join("path", "to", "file")

'path/to/file'

In [14]:
import numpy as np


In [127]:
x_arr = np.array([3,1,2])
y_arr = np.array([4,5,6])
z_arr = x_arr * y_arr # or -, *, /, £
z_arr

array([12,  5, 12])

In [52]:
x_arr[::-1].sort()

In [59]:
np.matmul(x_arr, y_arr)

28

In [128]:
x_arr.shape

x_y_stack = np.hstack([x_arr, y_arr])
x_y_stack.shape

(6,)

In [64]:
import scipy as sp

In [68]:
sp.stats.mode(np.array([3,1,2,2,3,3,5,3]))

/var/folders/gr/g48q79xn4_v4bpb8clswnyvw0000gp/T/ipykernel_2781/1558121490.py:1: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  sp.stats.mode(np.array([3,1,2,2,3,3,5,3]))[0]


array([3])

In [70]:
np.percentile(x_arr, 50)

3.0

In [98]:
x_seq = np.arange(1,12,1)

In [92]:
np.tile(x_arr, reps=2,)

array([3, 2, 1, 3, 2, 1])

In [99]:
x_seq[0:10]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [151]:
x_arr = np.array([1,2,3,np.nan])
print(x_arr)
x_arr[np.isnan(x_arr)] = 4

[ 1.  2.  3. nan]


In [152]:
x_arr

array([1., 2., 3., 4.])

In [147]:
x_arr + 1

array([ 2.,  3.,  4., nan])

In [107]:
np.insert(x_arr, obj=2, values=[1,2,3], )

array([ 1.,  2.,  1.,  2.,  3.,  3., nan])

In [109]:
x_arr[-1]

nan

In [110]:
np.delete(x_arr, obj=-1)

array([1., 2., 3.])

In [120]:
x_arr = np.array([(1,2,3),(4,5,6)])
print(x_arr)

[[1 2 3]
 [4 5 6]]


In [125]:
x_arr[:, 2]

array([3, 6])

In [140]:
for x in range(1,10):
    if x in [2,3,4]:
        print("good")

good
good
good


In [144]:
true_array = x_arr < 3
true_array

array([False,  True,  True])

In [143]:
true_array + 1

array([1, 2, 2])

In [149]:
np.isnan(x) 

True

In [148]:
n1 = float("nan")
n2 = float("Nan")
n3 = float("NaN")
n4 = float("NAN")
print(n1, n2, n3, n4)

nan nan nan nan


In [154]:
print("halo \t world")

halo 	 world


In [163]:
"Halli Hallo".find("Hallo")

6

In [166]:
" ".join(["Halli", "Hallo"])

'Halli Hallo'

In [167]:
abs(-5)

5

In [168]:
import math

In [170]:
math.floor(4.3)

4

In [171]:
4**2

16

In [173]:
10 % 3

1

In [175]:
10 // 3

3

In [178]:
int(4.5)

4

In [181]:
type(x)

int

In [180]:
complex(4.5)

(4.5+0j)

In [183]:
import pandas as pd

In [222]:
df = pd.DataFrame(
{"col1" : [1,2,3],
"col2" : [12.4, 15.6, 16.9],
"col3" : ["green", "blue", "white"]})

In [188]:
df.columns = ["rank", "result", "team"]

In [189]:
df

rank  result   team
0     1    12.4  green
1     2    15.6   blue
2     3    16.9  white

In [202]:
df.team

0    green
1     blue
2    white
Name: team, dtype: object

In [210]:
df.loc[len(df)] = [4, 12.0, "black"]

In [221]:
df

col1  col2   col3      3 new_col
0     1  12.4  green      4  junior
1     2  15.6   blue   12.0  senior
2     3  16.9  white  black  senior

In [213]:
df.loc[:, len(df.columns)] = [4, 12.0, "black"]

In [215]:
df["new_col"] = ["junior", "senior", "senior"]

In [219]:
df.iloc[:,1:]

col2   col3      3 new_col
0  12.4  green      4  junior
1  15.6   blue   12.0  senior
2  16.9  white  black  senior

In [220]:
df["col2"].idxmax()

2

In [224]:
df["col3"] = df["col3"].astype("category")

In [225]:
df["col3"].value_counts()

blue     1
green    1
white    1
Name: col3, dtype: int64

In [229]:
x = 7

if x < 5:
    print("small")
elif x < 10:
    print("medium")
else: 
    print("big")

medium


In [230]:
while(x < 10):
    x += 1
    print(x)

8
9
10


In [231]:
x_list = [1,2,3]

for x in x_list:
    print(x)

1
2
3


In [237]:
def my_func(first_name, last_name = ""):
    greeting = " ".join(["Hallo", first_name, last_name])
    print(greeting)
    return greeting

In [240]:
my_func("Donald", "Duck")

Hallo Donald Duck


'Hallo Donald Duck'